FROM public.ecr.aws/sam/build-provided.al2:latest

ENV PATH=$PATH:/usr/local/opt/sam-cli/bin:/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin
# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install --update && rm awscliv2.zip && rm -rf ./aws

# Install Rust toolchain
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
